version: '2'
services:
  mfsmaster:
    image: moosefs/master
    # build: ./moosefs-master
    container_name: "mfsmaster"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.2"
  mfsclient:
    image: moosefs/client
    # build: ./moosefs-client
    container_name: "mfsclient"
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.5"
  mfschunkserver1:
    image: moosefs/chunkserver
    # build: ./moosefs-chunkserver
    container_name: "mfschunkserver1"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.11"
  mfschunkserver2:
    image: moosefs/chunkserver
    # build: ./moosefs-chunkserver
    container_name: "mfschunkserver2"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.12"
  mfschunkserver3:
    image: moosefs/chunkserver
    # build: ./moosefs-chunkserver
    container_name: "mfschunkserver3"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.13"
  mfschunkserver4:
    image: moosefs/chunkserver
    # build: ./moosefs-chunkserver
    container_name: "mfschunkserver4"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.14"
  mfschunkserver5:
    image: moosefs/chunkserver
    # build: ./moosefs-chunkserver
    container_name: "mfschunkserver5"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.15"
networks:
  mfsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
