version: '2'

services:
  master:
    image: moosefs/master  #use GitHub version
    #build: ./moosefs-master  #use local version
    container_name: "master"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.2"
  client:
    image: moosefs/client  #use GitHub version
    #build: ./moosefs-client  #use local version
    container_name: "client"
    privileged: true
    stdin_open: true
    tty: true
    networks:
      mfsnet:
        ipv4_address: "172.20.0.5"
  chunkserver1:
    image: moosefs/chunkserver  #use GitHub version
    #build: ./moosefs-chunkserver  #use local version
    container_name: "chunkserver1"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.11"
  chunkserver2:
    image: moosefs/chunkserver  #use GitHub version
    #build: ./moosefs-chunkserver  #use local version
    container_name: "chunkserver2"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.12"
  chunkserver3:
    image: moosefs/chunkserver  #use GitHub version
    #build: ./moosefs-chunkserver  #use local version
    container_name: "chunkserver3"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.13"
  chunkserver4:
    image: moosefs/chunkserver  #use GitHub version
    #build: ./moosefs-chunkserver  #use local version
    container_name: "chunkserver4"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.14"
  chunkserver5:
    image: moosefs/chunkserver  #use GitHub version
    #build: ./moosefs-chunkserver  #use local version
    container_name: "chunkserver5"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.15"
networks:
  mfsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
