version: '2'

services:
  master:
    build: ./moosefs-master
    container_name: "master"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.2"
  client:
    build: ./moosefs-client
    container_name: "client"
    privileged: true
    stdin_open: true
    tty: true
    networks:
      mfsnet:
        ipv4_address: "172.20.0.5"
  chunkserver1:
    build: ./moosefs-chunkserver
    container_name: "chunkserver1"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.11"
  chunkserver2:
    build: ./moosefs-chunkserver
    container_name: "chunkserver2"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.12"
  chunkserver3:
    build: ./moosefs-chunkserver
    container_name: "chunkserver3"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.13"
  chunkserver4:
    build: ./moosefs-chunkserver
    container_name: "chunkserver4"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.14"
  chunkserver5:
    build: ./moosefs-chunkserver
    container_name: "chunkserver5"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.15"
networks:
  mfsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
